### ISSUE TITLE
Need help! I got the error " A JSON text must at least contain two octets! (JSON::ParserError)" when exec ./script/regenerate

### ISSUE THREAD

**Issue by mopduan** [github/gemoji#104]
the detail error message as follow:

```
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `new'
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /Users/FE/code/github/gemoji/lib/emoji.rb:84:in `block in parse_data_file'
	from /Users/FE/code/github/gemoji/lib/emoji.rb:84:in `open'
	from /Users/FE/code/github/gemoji/lib/emoji.rb:84:in `parse_data_file'
	from /Users/FE/code/github/gemoji/lib/emoji.rb:23:in `all'
	from db/dump.rb:57:in `<main>'
 db/emoji.json | 22561 --------------------------------------------------------
 1 file changed, 22561 deletions(-)
```

Thanks a lot!

**Comment by mislav** [comment]
Sorry, `script/regenerate` and `db/dump.rb` are a little bit broken right now, and in the works for the final release! However, you shouldn't need those scripts as a user of gemoji library, since `db/emoji.json` is already full generated and wel-formatted.

**Comment by mopduan** [comment]
That means if I want to get the skin tone emoji, I should use the emoji.json and code of https://github.com/s0meone/gemoji? 

Thanks for your help!

**Comment by mislav** [comment]
Yeah, until that's merged, feel free to use the fork!

**Comment by mopduan** [comment]
Thanks!
